name: Pull request checks

on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run test:lint

  tests:
    name: Functional Tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [18]
    needs: [lint]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install kourou
        run: npm install -g kourou

      - name: Install dependencies
        run: npm ci

      - name: run test
        run: npm run test:unit

      - name: functional tests
        run: bash test/kuzzle-vault-encrypt-string.test.sh
